server:
  port: 9006
#spring:
#  security:
#    user:
#      name:
#      password:
#      roles: ADMIN,USER
#security:
#  oauth2:
#    client:
#      client-id: mobile
#      client-secret: pin
#      access-token-validity-seconds: 3600
#      autherized-grant-types: refresh_token,authorization_code,password,clients_credintials
#      scope: READ,WRITE
#    authorization:
#      check-token-access: permitAll
