server:
   port: 9001

spring:
 datasource:
  url: jdbc:sqlserver://localhost;databasename=ems_db
  username: user
  password: pass
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  initialization-mode: always
 jpa:
  show-sql: true
  hibernate:
   dialect: org.hibernate.dialect.SQLServer2012Dialect
   ddl-auto: create-drop
 
 
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9006/oauth/check_token
    client:
      client-id: client
      client-secret: secret