server:
   port: 9003

spring:
 datasource:
  url: jdbc:sqlserver://localhost;databasename=ems_db
  username: user
  password: pass
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  initialization-mode: always
 jpa:
  show-sql: true
  hibernate:
   dialect: org.hibernate.dialect.SQLServer2012Dialect
   ddl-auto: create-drop