server:
 port: 9000
 servlet:
  session:
   cookie:
    name: KSESSIONID
 
#security:
#  oauth2:
#    client:
#      client-id: client
#      client-secret: secret
#      user-authorization-uri: http://localhost:9006/oauth/authorize
#      access-token-uri: http://localhost:9006/oauth/token
#    resource:
#      token-info-uri: http://localhost:9006/oauth/check_token
 

#security:
#  oauth2:
#    client:
#      clientId: b1184cb30670a052358f
#      clientSecret: c7ad98a019595df2e15f56f72c332916bee80d4c
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form
#      scope: READ,WRITE
#    resource:
#      user-info-uri: https://api.github.com/user
#      prefer-token-info: false

employee:
 service:
  url: http://localhost:9001
project:
 service:
  url: http://localhost:9002
task:
 service:
  url: http://localhost:9003
webapp:
 home:
  url: http://localhost:3000 
#security:
#  oauth2:
#    client:
#      client-id: client
#      client-Secret: secret
#      access-token-uri: http://localhost:9000/oauth/access_token
#      user-authorization-uri: http://localhost:9000/oauth/authorize
#     clientAuthenticationScheme: form
#    resource:
#      user-info-uri: http://localhost:9000/oauth/check_token
#      prefer-token-info: false
